// spa-sample-react-js/src/features/languages/components/Timeline.jsx
//import TimelineEntryEntity from '../entities/TimelineEntryEntity';
import { numberSorterService, stringSorterService } from '../services/TimelineSorterServices';



export default function Timeline(props) {

	let title = 'Timeline';

	let _entries = [];

	let sortBy = 'year';

	function setEntries(entries) {

		let sortedEntries = [];

		switch (sortBy) {
			case 'name':
				sortedEntries = entries.sort(stringSorterService);
				break;
			case 'date':
				sortedEntries = entries.sort(numberSorterService);
				break;
			default:
				sortedEntries = entries;
				break;
		}

		_entries = sortedEntries;

	}

	setEntries(props.entries);

	return (
		<>
			<h2>{title}</h2>
			{ _entries.length > 0 &&
				_entries.map((entry) =>
					<li key={entry.name}>{/* Each item in a loop must have an unique identifier */}
						{entry.name} - {entry.year}
					</li>
				)
			}
		</>
	);

}

// spa-sample-angular-ts/src/app/languages/timeline/timeline.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { TimelineSorterService } from '../services/timeline-sorter.service';

@Component({
	selector: 'timeline',
	templateUrl: './timeline.component.html',
	styleUrls: ['./timeline.component.scss']
})
export class TimelineComponent implements OnInit {

	@Input() title:string = 'Timeline';

	@Input()
	get entries():Array<{ name: string; year:number }> { return this._entries; }

	set entries(entries:Array<{ name: string; year:number }>) {

		let sortedEntries:Array<{ name: string; year:number }> = [];

		switch (this.sortBy) {
			case 'name':
				sortedEntries = entries.sort(this.timelineSorterService.stringSorter);
				break;
			case 'date':
				sortedEntries = entries.sort(this.timelineSorterService.numberSorter);
				break;
			default:
				sortedEntries = entries;
				break;
		}

		this._entries = sortedEntries;

	}

	private _entries:Array<{ name: string; year:number }> = [];

	@Input() sortBy:string = 'date';

	constructor(
		private timelineSorterService:TimelineSorterService
		) {

	}

	ngOnInit(): void {
	}

}

<p>timeline works!</p>

<ng-container>
	<h2>{{title}}</h2>
	<ul *ngIf='entries'>
		<li *ngFor='let entry of entries'>
			{{entry.name}} - {{entry.year}}
		</li>
	</ul>
</ng-container>
